---
- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "PQZ8Q~XSmMsU4dbgk2KyWMHK1h8X7ciD~H.1_csi"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    domain: "amitomar63gmail.onmicrosoft.com"

  tasks:
    - name: Set Payload Variables
      set_fact:
        default_user_name: "{{ awx_webhook_payload.displayName | default('') }}"
        default_mail_nickname: "{{ awx_webhook_payload.displayName.split(' ')[1:] | join('') | default('') }}"
        default_group_name: "{{ awx_webhook_payload.groupName | default('') }}"
        default_role_name: "{{ awx_webhook_payload.roleName | default('') }}"

    - name: Parse Display Name into First and Last Name
      set_fact:
        first_name: "{{ default_user_name.split(' ')[0] }}"
        last_name: "{{ default_user_name.split(' ')[1:] | join(' ') }}"
      when: default_user_name is defined and ' ' in default_user_name

    - name: Extract base mail nickname (without any numbers at the end)
      set_fact:
        base_mail_nickname: "{{ default_mail_nickname | regex_replace('\\d+$', '') }}"

    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response

    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"
        final_mail_nickname: "{{ base_mail_nickname }}"
        final_display_name: "{{ default_user_name }}"

    - name: Check if username already exists
      uri:
        url: "{{ graph_api_endpoint }}/users/{{ base_mail_nickname }}@{{ domain }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        status_code: [200, 404]
        return_content: yes
      register: initial_user_check
      ignore_errors: yes

    - name: Sequential username search if original exists
      when: initial_user_check.status == 200
      block:
        - name: Initialize counter
          set_fact:
            username_counter: 1

        - name: Find an available username
          until: username_check.status == 404
          retries: 20
          delay: 1
          block:
            - name: Check username availability
              uri:
                url: "{{ graph_api_endpoint }}/users/{{ base_mail_nickname }}{{ username_counter }}@{{ domain }}"
                method: GET
                headers:
                  Authorization: "Bearer {{ access_token }}"
                  Content-Type: "application/json"
                status_code: [200, 404]
                return_content: yes
              register: username_check
              ignore_errors: yes

            - name: Increment counter if username exists
              set_fact:
                username_counter: "{{ username_counter | int + 1 }}"
              when: username_check.status == 200

        - name: Set final username with counter
          set_fact:
            final_mail_nickname: "{{ base_mail_nickname }}{{ username_counter }}"
            final_display_name: "{{ default_user_name }} {{ username_counter }}"

    - name: Create User in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ final_display_name }}"
          givenName: "{{ first_name | default(default_user_name) }}"
          surname: "{{ last_name | default('') }}"
          mailNickname: "{{ final_mail_nickname }}"
          userPrincipalName: "{{ final_mail_nickname }}@{{ domain }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "Default@1234"
        body_format: json
        status_code: [201, 200]
      register: user_creation
      failed_when: user_creation.status not in [200, 201]

    - name: Debug User Creation Status
      debug:
        msg:
          - "User Creation Status: {{ user_creation.status }}"
          - "Response Body: {{ user_creation.json | default('No JSON response') }}"
          - "Error Details: {{ user_creation.json.error.message | default('Unknown error') }}"

    - name: Assign Group (if specified)
      when: default_group_name is defined and default_group_name != ''
      block:
        - name: Get Group ID by Name
          uri:
            url: "{{ graph_api_endpoint }}/groups?$filter=displayName eq '{{ default_group_name }}'"
            method: GET
            headers:
              Authorization: "Bearer {{ access_token }}"
              Content-Type: "application/json"
            return_content: yes
          register: group_lookup

        - name: Add User to Group
          uri:
            url: "{{ graph_api_endpoint }}/groups/{{ group_lookup.json.value[0].id }}/members/$ref"
            method: POST
            headers:
              Authorization: "Bearer {{ access_token }}"
              Content-Type: "application/json"
            body:
              "@odata.id": "{{ graph_api_endpoint }}/directoryObjects/{{ user_creation.json.id }}"
            body_format: json
            status_code: [204]
          when: group_lookup.json.value | length > 0

    - name: Final Debug Information
      debug:
        msg:
          - "First Name: {{ first_name | default('Not Set') }}"
          - "Last Name: {{ last_name | default('Not Set') }}"
          - "Base Mail Nickname: {{ base_mail_nickname }}"
          - "Final Mail Nickname: {{ final_mail_nickname }}"
          - "Final Display Name: {{ final_display_name }}"
          - "Group: {{ default_group_name | default('No Group Specified') }}"
