---
- name: Fetch Pending ServiceNow Requests and Create Users in Azure
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "{client_secret}"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"

  tasks:
    - name: Fetch requested item details from ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query=number=RITM0010017&sysparm_display_value=true&sysparm_exclude_reference_link=true"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: ritm_response
      failed_when: ritm_response.json.result is not defined or ritm_response.json.result | length == 0

    - name: Extract sys_id from request item
      set_fact:
        request_item_sys_id: "{{ ritm_response.json.result[0]['sys_id'] }}"
      when: ritm_response.json.result | length > 0

    - name: Fetch catalog variables from ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option?sysparm_query=request_item={{ request_item_sys_id }}&sysparm_display_value=true"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: catalog_response
      failed_when: catalog_response.json.result is not defined or catalog_response.json.result | length == 0

    - name: Debug Full Catalog Variables Response
      debug:
        msg: "{{ catalog_response.json.result }}"
      when: catalog_response.json.result | length > 0

    - name: Extract catalog variables
      set_fact:
        display_name: "{{ catalog_response.json.result | selectattr('item_option_new.name', 'equalto', 'DisplayName') | map(attribute='value') | first | default('') }}"
        mail_nickname: "{{ catalog_response.json.result | selectattr('item_option_new.name', 'equalto', 'mailNickname') | map(attribute='value') | first | default('') }}"
        user_principal_name: "{{ catalog_response.json.result | selectattr('item_option_new.name', 'equalto', 'userPrincipalName') | map(attribute='value') | first | default('') }}"
        user_password: "{{ catalog_response.json.result | selectattr('item_option_new.name', 'equalto', 'Password') | map(attribute='value') | first | default('TemporaryP@ssword!') }}"
      when: catalog_response.json.result | length > 0

    - name: Display extracted user details
      debug:
        msg: |
          Extracted User Details:
          Display Name: {{ display_name }}
          Mail Nickname: {{ mail_nickname }}
          User Principal Name: {{ user_principal_name }}
          Password: {{ user_password }}
