---
- name: Fetch Pending ServiceNow Requests and Create Users in Azure
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "{client_secret}"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
  tasks:
    - name: Fetch requested item details from ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query=number=RITM0010027"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: ritm_response
 
    - name: Fetch catalog item variables
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option_mtom?sysparm_query=request_item={{ ritm_response.json.result[0].sys_id }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: variables_response
 
    - name: Extract variable values
      set_fact:
        catalog_variables: "{{ {} }}"
      
    - name: Process each variable
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option?sysparm_query=sys_id={{ item.sc_item_option.value }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: variable_details
      loop: "{{ variables_response.json.result }}"
      
    - name: Map variable values
      set_fact:
        catalog_variables: "{{ catalog_variables | combine({variable_details.results[idx].json.result[0].item_option_new.display_value: variable_details.results[idx].json.result[0].value}) }}"
      loop_control:
        index_var: idx
      loop: "{{ variables_response.json.result }}"
 
    - name: Display request details
      debug:
        msg: |
          Request Number: {{ ritm_response.json.result[0].number }}
          DisplayName: {{ catalog_variables.DisplayName | default('N/A') }}
          mailNickname: {{ catalog_variables.mailNickname | default('N/A') }}
          userPrincipalName: {{ catalog_variables.userPrincipalName | default('N/A') }}
          Password: ********
 
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response
 
    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"
 
    - name: Create user in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ catalog_variables.DisplayName }}"
          mailNickname: "{{ catalog_variables.mailNickname }}"
          userPrincipalName: "{{ catalog_variables.userPrincipalName }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "{{ catalog_variables.Password | default('TemporaryP@ssword!') }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]  # Allow both success codes
      register: create_user_response
 
    - name: Update ServiceNow request item with completion status
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item/{{ ritm_response.json.result[0].sys_id }}"
        method: PATCH
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body:
          state: "3"  # Closed Complete
          work_notes: "User created in Azure AD: {{ create_user_response.json.userPrincipalName }}"
        body_format: json
        status_code: 200
      when: create_user_response is defined and create_user_response.status == 201
 
    - name: Display Azure user creation response
      debug:
        msg: "Azure User Created: {{ create_user_response.json }}"
