---
- name: Fetch Pending ServiceNow Requests and Create Users in Azure with Group and Role Assignment
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "{client_secret}"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    catalog_variables: {}
    request_id: "{request_id}"
  tasks:
    - name: Set query parameter based on input format
      set_fact:
        query_param: >-
          {% if request_id.startswith('RITM') %}number={{ request_id }}{% else %}sys_id={{ request_id }}{% endif %}
 
    - name: Fetch requested item details from ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query={{ query_param }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: ritm_response
    
    - name: Ensure RITM response contains results
      fail:
        msg: "No results found for request ID {{ request_id }}"
      when: ritm_response.json.result | length == 0
    
    - name: Extract sys_id from RITM response
      set_fact:
        request_sys_id: "{{ ritm_response.json.result[0].sys_id }}"
    
    - name: Fetch catalog item variables
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option_mtom?sysparm_query=request_item={{ request_sys_id }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: variables_response
    
    - name: Extract catalog variables
      set_fact:
        catalog_variables: "{{ variables_response.json.result | items2dict(key_name='item_option.value', value_name='value') }}"
    
    - name: Display extracted variables
      debug:
        var: catalog_variables
    
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response
    
    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"
    
    - name: Create user in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ catalog_variables['DisplayName'] }}"
          surname: "{{ catalog_variables['lastname'] | default('') }}"
          givenName: "{{ catalog_variables['firstname'] | default('') }}"
          mailNickname: "{{ catalog_variables['mailNickname'] }}"
          userPrincipalName: "{{ catalog_variables['userPrincipalName'] }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "{{ catalog_variables['Password'] }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: create_user_response
    
    - name: Ensure user creation was successful
      fail:
        msg: "User creation failed in Azure AD"
      when: create_user_response.status not in [200, 201]
    
    - name: Get directory roles
      uri:
        url: "{{ graph_api_endpoint }}/directoryRoles"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        return_content: yes
      register: roles_response
    
    - name: Find role ID for the requested role
      set_fact:
        role_id: "{{ (roles_response.json.value | selectattr('displayName', 'equalto', catalog_variables['RoleName']) | list | first).id | default('') }}"
      when: catalog_variables['RoleName'] is defined
    
    - name: Assign role to user
      uri:
        url: "{{ graph_api_endpoint }}/directoryRoles/{{ role_id }}/members/$ref"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          "@odata.id": "{{ graph_api_endpoint }}/directoryObjects/{{ create_user_response.json.id }}"
        body_format: json
        status_code: [204]
      when: role_id | length > 0
