---
- name: Fetch Pending ServiceNow Requests and Create Users in Azure with Group and Role Assignment
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "your_password_here"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "your_client_secret_here"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    request_id: "RITM123456"  # Ensure you pass a valid request ID
    catalog_variables: {}
  tasks:
    - name: Validate request_id
      fail:
        msg: "Request ID is not set. Please provide a valid request_id."
      when: request_id is not defined or request_id | trim == ""
    
    - name: Set query parameter based on request_id format
      set_fact:
        query_param: "number={{ request_id }}" if request_id.startswith('RITM') else "sys_id={{ request_id }}"
      
    - name: Fetch requested item details from ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query={{ query_param }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: ritm_response
      
    - name: Debug ritm_response
      debug:
        var: ritm_response
      
    - name: Extract sys_id from ritm_response
      set_fact:
        ritm_sys_id: "{{ ritm_response.json.result[0].sys_id | default('') }}"
      when: ritm_response.json.result | length > 0
      
    - name: Fail if no valid ServiceNow request item found
      fail:
        msg: "No valid ServiceNow request item found for query: {{ query_param }}"
      when: ritm_sys_id | trim == ""
      
    - name: Fetch catalog item variables
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option_mtom?sysparm_query=request_item={{ ritm_sys_id }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: variables_response
      when: ritm_sys_id | trim != ""
      
    - name: Extract and map variables
      set_fact:
        catalog_variables: "{{ catalog_variables | combine({ item.value: item.sc_item_option.value }) }}"
      loop: "{{ variables_response.json.result | default([]) }}"
      when: variables_response.json.result | length > 0
      
    - name: Display extracted variables
      debug:
        var: catalog_variables
      
    - name: Ensure required catalog variables are present
      fail:
        msg: "Required catalog variables are missing (DisplayName, mailNickname, userPrincipalName, Password)."
      when:
        - catalog_variables['DisplayName'] is not defined
        - catalog_variables['mailNickname'] is not defined
        - catalog_variables['userPrincipalName'] is not defined
        - catalog_variables['Password'] is not defined
      
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response
      
    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"
      when: azure_auth_response.json.access_token is defined
      
    - name: Create user in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ catalog_variables['DisplayName'] }}"
          surname: "{{ catalog_variables['lastname'] | default('') }}"
          givenName: "{{ catalog_variables['firstname'] | default('') }}"
          mailNickname: "{{ catalog_variables['mailNickname'] }}"
          userPrincipalName: "{{ catalog_variables['userPrincipalName'] }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "{{ catalog_variables['Password'] }}"
        body_format: json
        status_code: [200, 201]
      register: create_user_response
      
    - name: Add user to Azure AD group if specified
      uri:
        url: "{{ graph_api_endpoint }}/groups/{{ catalog_variables['GroupID'] }}/members/$ref"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          "@odata.id": "{{ graph_api_endpoint }}/directoryObjects/{{ create_user_response.json.id }}"
        body_format: json
        status_code: [204]
      when:
        - catalog_variables['GroupID'] is defined
        - create_user_response.status in [200, 201]
      
    - name: Debug final user creation response
      debug:
        var: create_user_response
