---
- name: Fetch Pending ServiceNow Requests and Create Users in Azure
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "{client_secret}"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"

  tasks:
    - name: Fetch requested item details from ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query=number=RITM0010017"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: ritm_response
      failed_when: ritm_response.json.result is not defined or ritm_response.json.result | length == 0

    - name: Extract catalog variables from request item
      set_fact:
        display_name: "{{ ritm_response.json.result[0]['variables'].get('DisplayName', '') }}"
        mail_nickname: "{{ ritm_response.json.result[0]['variables'].get('mailNickname', '') }}"
        user_principal_name: "{{ ritm_response.json.result[0]['variables'].get('userPrincipalName', '') }}"
        user_password: "{{ ritm_response.json.result[0]['variables'].get('Password', 'TemporaryP@ssword!') }}"
      when: ritm_response.json.result | length > 0

    - name: Display extracted user details from catalog variables
      debug:
        msg: |
          Extracted User Details:
          Display Name: {{ display_name }}
          Mail Nickname: {{ mail_nickname }}
          User Principal Name: {{ user_principal_name }}
          Password: {{ user_password }}

    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response
      failed_when: azure_auth_response.json.access_token is not defined

    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"

    - name: Create user in Azure AD
      when: display_name != '' and mail_nickname != '' and user_principal_name != ''
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ display_name }}"
          mailNickname: "{{ mail_nickname }}"
          userPrincipalName: "{{ user_principal_name }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "{{ user_password }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]
      register: create_user_response
      failed_when: create_user_response.json.id is not defined

    - name: Display Azure user creation response
      when: create_user_response.json is defined
      debug:
        msg: "Azure User Created: {{ create_user_response.json }}"
