---
- name: Fetch Pending ServiceNow Requests and Create Users in Azure
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "{client_secret}"
    sys_id: "{sys_id}"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    catalog_variables: {}
  tasks:
    - name: Fetch requested item details from ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query=number={{sys_id}}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: ritm_response
 
    - name: Fetch catalog item variables
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option_mtom?sysparm_query=request_item={{ ritm_response.json.result[0].sys_id }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: variables_response
      
    - name: Fetch variable details for each option
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_item_option/{{ item.sc_item_option.value }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: option_value_details
      loop: "{{ variables_response.json.result }}"
      
    - name: Extract variable values and IDs
      set_fact:
        variable_values: "{{ variable_values | default([]) + [{'value': item.json.result.value, 'item_option_id': item.json.result.item_option_new.value}] }}"
      loop: "{{ option_value_details.results }}"
      
    - name: Fetch variable names for each option
      uri:
        url: "{{ servicenow_instance }}/api/now/table/item_option_new/{{ item.item_option_id }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: option_name_details
      loop: "{{ variable_values }}"
      
    - name: Create catalog variables dictionary
      set_fact:
        catalog_variables: "{{ catalog_variables | combine({item.0.json.result.question_text: item.1.value}) }}"
      loop: "{{ option_name_details.results | zip(variable_values) | list }}"
      
    - name: Display extracted variables
      debug:
        var: catalog_variables
 
    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response
 
    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"
 
    - name: Create user in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          accountEnabled: true
          displayName: "{{ catalog_variables.DisplayName }}"
          mailNickname: "{{ catalog_variables.mailNickname }}"
          userPrincipalName: "{{ catalog_variables.userPrincipalName }}"
          passwordProfile:
            forceChangePasswordNextSignIn: true
            password: "{{ catalog_variables.Password | default('TemporaryP@ssword!') }}"
        body_format: json
        return_content: yes
        status_code: [200, 201]  # Allow both success codes
      register: create_user_response
 
    - name: Update ServiceNow request item with completion status
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item/{{ ritm_response.json.result[0].sys_id }}"
        method: PATCH
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body:
          state: "3"  # Closed Complete
          work_notes: "User created in Azure AD: {{ create_user_response.json.userPrincipalName }}"
        body_format: json
        status_code: 200
      when: create_user_response is defined and create_user_response.status == 201
 
    - name: Display Azure user creation response
      debug:
        msg: "Azure User Created: {{ create_user_response.json }}"
