---
- name: Fetch Pending ServiceNow Requests
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "PQZ8Q~XSmMsU4dbgk2KyWMHK1h8X7ciD~H.1_csi"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    domain: "amitomar63gmail.onmicrosoft.com"

  tasks:
    - name: Set Payload Variables
      set_fact:
        default_user_name: "{{ awx_webhook_payload.displayName | default('') }}"
        default_mail_nickname: "{{ awx_webhook_payload.displayName.split(' ')[1:] | join('') | default('') }}"
        default_group_name: "{{ awx_webhook_payload.groupName | default('') }}"
        default_role_name: "{{ awx_webhook_payload.roleName | default('') }}"

    - name: Debug Initial Payload
      debug:
        msg:
          - "Display Name: {{ default_user_name }}"
          - "Mail Nickname: {{ default_mail_nickname }}"
          - "Group Name: {{ default_group_name }}"
          - "Role Name: {{ default_role_name }}"

    - name: Parse Display Name into First and Last Name
      set_fact:
        first_name: "{{ default_user_name.split(' ')[0] }}"
        last_name: "{{ default_user_name.split(' ')[1:] | join(' ') }}"
      when: default_user_name is defined and ' ' in default_user_name

    - name: Extract base mail nickname (without any numbers at the end)
      set_fact:
        base_mail_nickname: "{{ default_mail_nickname | regex_replace('\\d+$', '') }}"

    - name: Get Azure access token
      uri:
        url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
        method: POST
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "https://graph.microsoft.com/.default"
          grant_type: "client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: azure_auth_response

    - name: Set Azure token
      set_fact:
        access_token: "{{ azure_auth_response.json.access_token }}"
        final_mail_nickname: "{{ base_mail_nickname }}"
        final_display_name: "{{ default_user_name }}"

    - name: Check if original user exists in Azure AD
      uri:
        url: "{{ graph_api_endpoint }}/users/{{ base_mail_nickname }}@{{ domain }}"
        method: GET
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        status_code: [200, 404]
        return_content: yes
      register: initial_user_check
      ignore_errors: yes

    - name: Sequential username search if original exists
      when: initial_user_check.status == 200
      block:
        - name: Initialize counter
          set_fact:
            username_counter: 1

        - name: Check username availability with counter
          uri:
            url: "{{ graph_api_endpoint }}/users/{{ base_mail_nickname }}{{ username_counter }}@{{ domain }}"
            method: GET
            headers:
              Authorization: "Bearer {{ access_token }}"
              Content-Type: "application/json"
            status_code: [200, 404]
            return_content: yes
          register: username_check
          ignore_errors: yes
          until: username_check.status == 404
          retries: 20
          delay: 1

        - name: Increment counter after each check
          set_fact:
            username_counter: "{{ username_counter | int + 1 }}"
          when: username_check.status == 200

        - name: Set final username with counter
          set_fact:
            final_mail_nickname: "{{ base_mail_nickname }}{{ username_counter }}"
            final_display_name: "{{ default_user_name }} {{ username_counter }}"

    - name: Debug final username and display name
      debug:
        msg:
          - "Base username (without numbers): {{ base_mail_nickname }}"
          - "Original username: {{ default_mail_nickname }}"
          - "Original display name: {{ default_user_name }}"
          - "Final username to be used: {{ final_mail_nickname }}"
          - "Final display name to be used: {{ final_display_name }}"
          - "Username counter (if used): {{ username_counter | default('N/A') }}"
