---
- name: Fetch Pending ServiceNow Requests and Create Users in Azure
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "admin"
    servicenow_password: "%ml4Vs9RXE/s"
    tenant_id: "195e8969-c853-47b4-83d0-36e044d83923"
    client_id: "e2e46ae3-2dee-4eed-a074-ddffd760ab2b"
    client_secret: "{{ lookup('env', 'CLIENT_SECRET') }}"
    graph_api_endpoint: "https://graph.microsoft.com/v1.0"
    catalog_variables: {}
    request_id: "{{ lookup('env', 'REQUEST_ID') }}"  # Ensure this is passed from AWX extra vars

  tasks:
    - name: Validate request_id is provided
      fail:
        msg: "No request_id provided. Please pass the ServiceNow request ID."
      when: request_id is undefined or request_id | length == 0

    - name: Set query parameter based on input format
      set_fact:
        query_param: >-
          {% if request_id.startswith('RITM') %}number={{ request_id }}{% else %}sys_id={{ request_id }}{% endif %}

    - name: Fetch requested item details from ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query={{ query_param }}"
        method: GET
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        return_content: yes
      register: ritm_response

    - name: Debug ritm_response
      debug:
        var: ritm_response.json.result
      failed_when: ritm_response.json.result | length == 0

    # ... (rest of the existing playbook remains the same)
