---
 
- name: Reset a user’s password via Microsoft Graph
  hosts: localhost
  connection: local
  gather_facts: no
 

  vars:
    user_object_id: "{{ user_object_id | default('') }}"
    new_password: "{{ new_password | default('') }}"
    bearer_token: "eyJ0eXAiOiJKV1QiLCJub25jZSI6InRXRnpwT1RoYVBIM3hBYXpUNl84cWE3TURBclQwQTY4R25nd1o1X2pBdWsiLCJhbGciOiJSUzI1NiIsIng1dCI6ImltaTBZMnowZFlLeEJ0dEFxS19UdDVoWUJUayIsImtpZCI6ImltaTBZMnowZFlLeEJ0dEFxS19UdDVoWUJUayJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xOTVlODk2OS1jODUzLTQ3YjQtODNkMC0zNmUwNDRkODM5MjMvIiwiaWF0IjoxNzQxMjgzNDQyLCJuYmYiOjE3NDEyODM0NDIsImV4cCI6MTc0MTM3MDE0MiwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsicDEiXSwiYWlvIjoiQVZRQXEvOFpBQUFBaXZsSXFWMFBtRE9Cd245VEdQL01GekVuKzVBWm9OOWZYanMyTlZldnl0N05xTU5ZVFFydHJzNGJ4bG9kWDZveTZkWXJwN1dNbkpJelpvMUVmaFhMZU83TFVTUis0c2MrcXJKYmEyT2xxeDg9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJHcmFwaCBFeHBsb3JlciIsImFwcGlkIjoiZGU4YmM4YjUtZDlmOS00OGIxLWE4YWQtYjc0OGRhNzI1MDY0IiwiYXBwaWRhY3IiOiIwIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTY1LjIyNS4xMjAuMTUwIiwibmFtZSI6Ikdsb2JhbCBBZG1pbiIsIm9pZCI6ImQ4MTA4OTIyLWE1ZTEtNDE1Yi05NzRiLTkwMjJiYTRlNDkyZSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwNDQ0NTJBOUUzIiwicmgiOiIxLkFVb0FhWWxlR1ZQSXRFZUQwRGJnUk5nNUl3TUFBQUFBQUFBQXdBQUFBQUFBQUFBdUFlZEtBQS4iLCJzY3AiOiJBUElDb25uZWN0b3JzLlJlYWQuQWxsIEFQSUNvbm5lY3RvcnMuUmVhZFdyaXRlLkFsbCBvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWQgVXNlckF1dGhNZXRob2QtUGFzc2tleS5SZWFkV3JpdGUuQWxsIFVzZXItUGFzc3dvcmRQcm9maWxlLlJlYWRXcml0ZS5BbGwgZW1haWwgVXNlckF1dGhlbnRpY2F0aW9uTWV0aG9kLlJlYWRXcml0ZS5BbGwiLCJzaWQiOiIwMDJlYjkwOS1mZDkwLTFlMzktM2UwNC04ZTBiYjBiY2Q3NGUiLCJzdWIiOiJRRC1PMDk0Vm9qNVM0bGcwVWU0LVNNRzUtY0poZmtrbnQ3YkE4VjAySC0wIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiMTk1ZTg5NjktYzg1My00N2I0LTgzZDAtMzZlMDQ0ZDgzOTIzIiwidW5pcXVlX25hbWUiOiJHQWRtaW5AYW1pdG9tYXI2M2dtYWlsLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6IkdBZG1pbkBhbWl0b21hcjYzZ21haWwub25taWNyb3NvZnQuY29tIiwidXRpIjoiaGNpSl9GSTJ4ay1VUjFSXzJOUVJBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19jYyI6WyJDUDEiXSwieG1zX2Z0ZCI6IkZYdFlFNlk5ek9ua3BoNV9mYjBtUXZTZW9FbGZrMUtlTFFSLXJETF8td0UiLCJ4bXNfaWRyZWwiOiIxIDgiLCJ4bXNfc3NtIjoiMSIsInhtc19zdCI6eyJzdWIiOiJmZnVKZHpTVFQ1TC1NSjhYY002b2N4RW5DaVMtNTBOQVF0MWNqb212bVRzIn0sInhtc190Y2R0IjoxNjc4ODgwMDQwfQ.hAsdGjfYqpPKxakRhr-DYRXNqTi7k2ql7xgLeMmauG1PoR3dAjGDlvB6wT3EMu07PIRXHafsOh0eqeRSztHZ7MJOnMPdUaR3y4wdrpMZKcx32G9pXzp5n_a3HWPoyUGW9IXpF-EsC4bXkTnUk_s2v9vtRsFxuFX7Zsn9YrRbjOekwYaxTna0kaZxuYNRUycbYFJSlTQ7kDeNP1CuUiruxVBwalcfekcQqoFXDdeNRm9FbJQYEfjV84J2APtlA4hJTWc7yZjmd4u2mlkwBiPiDrclzDO865n2VeTWoIrEkeYuIaZo5m0W3DpO30595AvxdPJhIbqt7qmaRaFJ2lje-A"

 
  tasks:
    - name: Reset password
      uri:
        url: "https://graph.microsoft.com/v1.0/users/{{ 5539e8a2-40d4-4f15-a63f-d9114e9a64c2 }}/authentication/methods/28c10230-6103-485e-b985-444c60001490/resetPassword"
        method: POST
        headers:
          # Provide the token in the Bearer scheme
          Authorization: "Bearer {{ bearer_token }}"
          # Indicate that you're sending JSON in the request body
          Content-Type: "application/json"
        body: >
          {
              "newPassword": "{{ new_password }}"
          }
        body_format: json
        return_content: yes
        # By default, Ansible expects 200 or 201, etc.
        # Let's explicitly allow 202 as well:
        status_code: [200, 201, 202, 204]
        # So we can see the response
      register: graph_response
 
    - name: Print the Graph API response
      debug:
        var: graph_response
