- name: Reset Azure AD User Password
  hosts: localhost
  gather_facts: no
  vars:
    access_token: "eyJ0eXAiOiJKV1QiLCJub25jZSI6InRXRnpwT1RoYVBIM3hBYXpUNl84cWE3TURBclQwQTY4R25nd1o1X2pBdWsiLCJhbGciOiJSUzI1NiIsIng1dCI6ImltaTBZMnowZFlLeEJ0dEFxS19UdDVoWUJUayIsImtpZCI6ImltaTBZMnowZFlLeEJ0dEFxS19UdDVoWUJUayJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xOTVlODk2OS1jODUzLTQ3YjQtODNkMC0zNmUwNDRkODM5MjMvIiwiaWF0IjoxNzQxMjgzNDQyLCJuYmYiOjE3NDEyODM0NDIsImV4cCI6MTc0MTM3MDE0MiwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsicDEiXSwiYWlvIjoiQVZRQXEvOFpBQUFBaXZsSXFWMFBtRE9Cd245VEdQL01GekVuKzVBWm9OOWZYanMyTlZldnl0N05xTU5ZVFFydHJzNGJ4bG9kWDZveTZkWXJwN1dNbkpJelpvMUVmaFhMZU83TFVTUis0c2MrcXJKYmEyT2xxeDg9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJHcmFwaCBFeHBsb3JlciIsImFwcGlkIjoiZGU4YmM4YjUtZDlmOS00OGIxLWE4YWQtYjc0OGRhNzI1MDY0IiwiYXBwaWRhY3IiOiIwIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTY1LjIyNS4xMjAuMTUwIiwibmFtZSI6Ikdsb2JhbCBBZG1pbiIsIm9pZCI6ImQ4MTA4OTIyLWE1ZTEtNDE1Yi05NzRiLTkwMjJiYTRlNDkyZSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwNDQ0NTJBOUUzIiwicmgiOiIxLkFVb0FhWWxlR1ZQSXRFZUQwRGJnUk5nNUl3TUFBQUFBQUFBQXdBQUFBQUFBQUFBdUFlZEtBQS4iLCJzY3AiOiJBUElDb25uZWN0b3JzLlJlYWQuQWxsIEFQSUNvbm5lY3RvcnMuUmVhZFdyaXRlLkFsbCBvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWQgVXNlckF1dGhNZXRob2QtUGFzc2tleS5SZWFkV3JpdGUuQWxsIFVzZXItUGFzc3dvcmRQcm9maWxlLlJlYWRXcml0ZS5BbGwgZW1haWwgVXNlckF1dGhlbnRpY2F0aW9uTWV0aG9kLlJlYWRXcml0ZS5BbGwiLCJzaWQiOiIwMDJlYjkwOS1mZDkwLTFlMzktM2UwNC04ZTBiYjBiY2Q3NGUiLCJzdWIiOiJRRC1PMDk0Vm9qNVM0bGcwVWU0LVNNRzUtY0poZmtrbnQ3YkE4VjAySC0wIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiMTk1ZTg5NjktYzg1My00N2I0LTgzZDAtMzZlMDQ0ZDgzOTIzIiwidW5pcXVlX25hbWUiOiJHQWRtaW5AYW1pdG9tYXI2M2dtYWlsLm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6IkdBZG1pbkBhbWl0b21hcjYzZ21haWwub25taWNyb3NvZnQuY29tIiwidXRpIjoiaGNpSl9GSTJ4ay1VUjFSXzJOUVJBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19jYyI6WyJDUDEiXSwieG1zX2Z0ZCI6IkZYdFlFNlk5ek9ua3BoNV9mYjBtUXZTZW9FbGZrMUtlTFFSLXJETF8td0UiLCJ4bXNfaWRyZWwiOiIxIDgiLCJ4bXNfc3NtIjoiMSIsInhtc19zdCI6eyJzdWIiOiJmZnVKZHpTVFQ1TC1NSjhYY002b2N4RW5DaVMtNTBOQVF0MWNqb212bVRzIn0sInhtc190Y2R0IjoxNjc4ODgwMDQwfQ.hAsdGjfYqpPKxakRhr-DYRXNqTi7k2ql7xgLeMmauG1PoR3dAjGDlvB6wT3EMu07PIRXHafsOh0eqeRSztHZ7MJOnMPdUaR3y4wdrpMZKcx32G9pXzp5n_a3HWPoyUGW9IXpF-EsC4bXkTnUk_s2v9vtRsFxuFX7Zsn9YrRbjOekwYaxTna0kaZxuYNRUycbYFJSlTQ7kDeNP1CuUiruxVBwalcfekcQqoFXDdeNRm9FbJQYEfjV84J2APtlA4hJTWc7yZjmd4u2mlkwBiPiDrclzDO865n2VeTWoIrEkeYuIaZo5m0W3DpO30595AvxdPJhIbqt7qmaRaFJ2lje-A"  # Replace with a valid token
    password_reset_endpoint: "https://graph.microsoft.com/v1.0/users/5539e8a2-40d4-4f15-a63f-d9114e9a64c2/authentication/methods/28c10230-6103-485e-b985-444c60001490/resetPassword"
 
  tasks:
    - name: Reset Password via Microsoft Graph API
      uri:
        url: "{{ password_reset_endpoint }}"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          password: ""
          forceChangePasswordNextSignIn: true
        status_code: [202, 204]  # Accept both 202 (async) and 204 (success)
      register: password_reset_response
 
    - name: Extract new password if available
      set_fact:
        new_temp_password: "{{ password_reset_response.json.newPassword | default('Not Provided') }}"
 
    - name: Debug Password Reset Response
      debug:
        msg:
          - "Password reset attempted"
          - "Temporary Password: {{ new_temp_password }}"
          - "Response: {{ password_reset_response }}"
