---
- name: Reset Azure AD User Password using Microsoft Graph API
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "https://dev247928.service-now.com"
    servicenow_username: "{{ service_now_username }}"
    servicenow_password: "{{ service_now_password }}"
    request_item_sys_id: "{{ awx_webhook_payload.sysId }}"# Passed from AWX
    azure_ad_user_email: "{{ awx_webhook_payload.username }}"  # Passed from AWX
    servicenow_table: "sc_req_item"
    new_password: "{{ awx_webhook_payload.password }}"
    azure_tenant_id: "{{ azure_tenant_id }}"
    azure_client_id: "{{ azure_client_id }}"
    azure_client_secret: "{{ azure_client_secret }}"
  tasks:
    - name: Debug Webhook Payload
      debug:
        var: awx_webhook_payload

    - name: Get Microsoft Graph API Token
      uri:
        url: "https://login.microsoftonline.com/{{ azure_tenant_id }}/oauth2/v2.0/token"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body: "client_id={{ azure_client_id }}&client_secret={{ azure_client_secret }}&scope=https://graph.microsoft.com/.default&grant_type=client_credentials"
        body_format: form-urlencoded
        return_content: yes
      register: graph_token

    - name: Reset Azure AD User Password via Microsoft Graph API
      uri:
        url: "https://graph.microsoft.com/v1.0/users/{{ azure_ad_user_email }}"
        method: PATCH
        headers:
          Authorization: "Bearer {{ graph_token.json.access_token }}"
          Content-Type: "application/json"
        body: "{\"passwordProfile\": {\"forceChangePasswordNextSignIn\": true, \"password\": \"{{ new_password }}\"}}"
        body_format: json
        status_code: [200, 204]
      register: password_reset_result

    - name: Debug Password Reset Output
      debug:
        msg: "Password reset successful for {{ azure_ad_user_email }}"

    - name: Update ServiceNow record with license availability if user is created
      uri:
        url: "{{ servicenow_instance }}/api/now/table/{{ servicenow_table }}/{{ request_item_sys_id }}"
        method: PATCH
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body:
          correlation_id: "is_available"
        body_format: json
        return_content: yes
      when: password_reset_result.status in [200, 204]    
        
