- name: Reset Azure AD User Password
  hosts: localhost
  gather_facts: no
  vars:
    access_token: "eyJ0eXAiOiJKV1QiLCJub25jZSI6InRXRnpwT1RoYVBIM3hBYXpUNl84cWE3TURBclQwQTY4R25nd1o1X2pBdWsiLCJhbGciOiJSUzI1NiIsIng1dCI6ImltaTBZMnowZFlLeEJ0dEFxS19UdDVoWUJUayIsImtpZCI6ImltaTBZMnowZFlLeEJ0dEFxS19UdDVoWUJUayJ9..."
    password_reset_endpoint: "https://graph.microsoft.com/v1.0/users/5539e8a2-40d4-4f15-a63f-d9114e9a64c2/authentication/methods/28c10230-6103-485e-b985-444c60001490/resetPassword"

  tasks:
    - name: Prompt for New Password
      pause:
        prompt: "Enter the new password for the user:"
      register: user_input

    - name: Store the Provided Password
      set_fact:
        user_provided_password: "{{ user_input.user_input }}"

    - name: Reset Password via Microsoft Graph API
      uri:
        url: "{{ password_reset_endpoint }}"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          password: "{{ user_provided_password }}"
          forceChangePasswordNextSignIn: true
        status_code: [202, 204]
      register: password_reset_response

    - name: Debug Password Reset Response
      debug:
        msg:
          - "Password reset attempted"
          - "Response: {{ password_reset_response }}"

    - name: Fetch Password from ServiceNow
      uri:
        url: "https://dev247928.service-now.com/api/now/table/sc_request?sysparm_query=number=REQ0010366"
        method: GET
        headers:
          Authorization: "Basic {{ lookup('env', 'SNOW_AUTH') }}"
          Content-Type: "application/json"
        return_content: yes
        status_code: [200]
      register: servicenow_response

    - name: Extract Password from ServiceNow Response
      set_fact:
        retrieved_password: "{{ servicenow_response.json.result[0].u_new_password | default('Not Available') }}"

    - name: Debug Retrieved Password
      debug:
        msg: "Fetched Password: {{ retrieved_password }}"
