- name: Reset Azure AD User Password
  hosts: localhost
  gather_facts: no
  vars:
    tenant_id: "your-tenant-id"
    client_id: "your-client-id"
    client_secret: "your-client-secret"
    scope: "https://graph.microsoft.com/.default"
    token_url: "https://login.microsoftonline.com/{{ tenant_id }}/oauth2/v2.0/token"
    password_reset_endpoint: "https://graph.microsoft.com/v1.0/users/d8108922-a5e1-415b-974b-9022ba4e492e/authentication/methods/28c10230-6103-485e-b985-444c60001490/resetPassword"

  tasks:
    - name: Get Access Token from Microsoft Identity Platform
      uri:
        url: "{{ token_url }}"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          grant_type: "client_credentials"
          scope: "{{ scope }}"
        body_format: form-urlencoded
        return_content: yes
      register: token_response

    - name: Extract Access Token
      set_fact:
        access_token: "{{ token_response.json.access_token }}"

    - name: Reset Password via Microsoft Graph API
      uri:
        url: "{{ password_reset_endpoint }}"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          password: ""
          forceChangePasswordNextSignIn: true
        status_code: [202, 204]
      register: password_reset_response

    - name: Extract new password if available
      set_fact:
        new_temp_password: "{{ password_reset_response.json.newPassword | default('Not Provided') }}"

    - name: Debug Password Reset Response
      debug:
        msg:
          - "Password reset attempted"
          - "Temporary Password: {{ new_temp_password }}"
          - "Response: {{ password_reset_response }}"
